config/routes.rb
Rails.application.routes.draw do

  # Dashboard routes
  resource :posts, only: [] do
    get  :view
    get  :invalid_names
    get  :refresh
    post :edit
  end
  root to: "posts#view"

  # Session routes
  resources :sessions , only: [:create, :destroy, :login]
  get 'auth/:provider/callback',       to: 'sessions#create'
  get 'auth/failure',                  to: redirect('/')
  get 'signout',                       to: 'sessions#destroy', as: 'signout'
  get 'signin',                        to: 'sessions#login',   as: 'signin'
end

app/models/post.rb
class Post < ApplicationRecord
  # Make sure that lists can be serialized as strings in the Rails DB
  serialize :challenges

  ##
  # Populate data fields for a new User object when it is initialized
  def init_actions(new_post)
    new_post.challenges ||= []
    challenges = new_post.challenges
    new_post.challenges = YAML.load(challenges) if challenges.class == String
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper

  before_filter :handle_show_processed

  def view
    if @show_processed
      @posts = Post.where(is_processed: true)
    else
      @posts = Post.where(is_processed: false)
    end
    @posts = @posts.sort_by { |post| date_to_int(post.timestamp) }.reverse
  end

  def invalid_names
    @posts = []
    GoogleSync.new.detect_mismatched_names.each do |team, team_posts|
      team_posts.each do |post|
        @posts << post
      end
    end
  end

  def edit
    @post = Post.find(params["post_id"])
    @post.challenges = params["challenges"].split(", ")
    @post.team = params["team"]
    @post.is_processed = params["is_processed"].to_i
    @post.save!
    redirect_back(fallback_location: view_posts_path)
 end

  def refresh
    posts = FbSync.new.update()

    num_posts = posts.length
    if num_posts == 0
      flash[:error] = "Unable to download posts - please contact Daniel Taipei"
    else
      flash[:notice] = "Downloaded #{num_posts} posts!"
    end
    redirect_to view_posts_path
  end

  private

  def handle_show_processed()
    @show_processed = params.has_key?(:show_processed) && (params[:show_processed] == "true")
  end
end

app/views/posts/_data_table.html.erb
          <% if @posts.length > 0 %>
            <ul class="collection">
              <% @posts.each do |post| %>
                    
                <li class="collection-item avatar">
                  <% post_message = post.message.split(" ") %>
                  <% post_message_hashtags = post_message.map { |word| word.starts_with?("#") ? "<strong>#{word}</strong>" : word } %>
                  <% post_message = post_message_hashtags.join(" ").html_safe %>
          
                  <img src="<%= post.profile_link %>" alt="" class="circle post_author_profile">
                  <span class="title post_author"><%= post.author %></span>
                  <p class="post_timestamp"><%= post.timestamp %></p>
                  <p class="post_message"><%= post_message %></p>
                  <p class="hidden_data">
                    <span class="post_id"><%= post.id %></span>
                    <span class="post_team"><%= post.team %></span>
                    <span class="post_challenges"><%= post.challenges == "" ? "" : post.challenges.join(", ") %></span>
                    <span class="post_is_processed"><%= post.is_processed %></span>
                  </p>

                  <button data-target="data-modal" class="waves-effect waves-light btn btn-small blue lighten-2 secondary-content modal-trigger">
                    <i class="material-icons left">edit</i>
                    Edit Post Points
                  </button>
                </li>
        
              <% end %>
            </ul>

            <div id="data-modal" class="modal modal-fixed-footer">
              <%= form_for "", url: edit_posts_path(1) do |f| %>
                <div class="modal-content">

                  <h5 class="modal_title">Edit Post Details</h5>
                  <div class="row">
                    <div class="col s6">
                      <img src="" class="circle edit_post_author_profile">
                      <h6 class="edit_post_author_label">Author:</h6>
                      <span class="edit_post_author"></span>
                    </div>
                    <div class="col s6">
                      <h6 class="edit_post_timestamp_label">Timestamp:</h6>
                      <span class="edit_post_timestamp"></span>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col s12">
                      <h6 class="edit_post_message_label">Message:</h6>
                      <span class="edit_post_message"></span>
                    </div>
                  </div>
                  <%= f.hidden_field :post_id, class: "edit_post_id" %>
                  <div class="row form_row">
                    <div class="col s6 input-field">
                      <%= f.label :team, class: "edit_post_team_label" %>
                      <%= f.text_field :team, class: "edit_post_team" %>
                    </div>
                    <div class="col s6 input-field">
                      <%= f.label :challenges, class: "edit_post_challenges_label" %>
                      <%= f.text_field :challenges, class: "edit_post_challenges" %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col s6 input-field">
                      <label>
                        <%= f.check_box :is_processed, class: "filled-in edit_post_is_processed" %>
                        <span>Is Processed</span>
                      </label>
                    </div>
                    <div class="col s6 input-field">
                      <label>
                      </label>
                    </div>
                  </div>

                </div>

                <div class="modal-footer">
                  <%= f.submit "Save", class: "waves-effect waves-green btn-flat green darken-2" %>
                </div>
              <% end %>
            </div>
<% end %>

app/views/posts/invalid_names.html.erb
<% view_posts_path_link = @show_processed ? view_posts_path(show_processed: true) : view_posts_path %>

<div class="table-options swap-modes">
  <%= link_to view_posts_path_link, class: "waves-effect waves-light btn-small indigo darken-4 table-option" do %>
    <i class="material-icons left">chevron_left</i>
    <%= @show_processed ? "Return to Processed Data" : "Return to Unprocessed Data" %>
  <% end %>
</div>
<div class="table-options">
  <%= link_to refresh_posts_path, class: "waves-effect waves-light btn-small orange darken-2 table-option" do %>
    <i class="material-icons left">sync</i>
    Update Site Data
  <% end %>
</div>

<% if @posts.length == 0 %>
  <div class="collection empty_collection">
    No Facebook posts with invalid names! Yay!
  </div>
<% end %>

app/views/posts/view.html.erb
<% view_posts_path_link = @show_processed ? view_posts_path : view_posts_path(show_processed: true) %>
<% invalid_names_posts_path_link = @show_processed ? invalid_names_posts_path(show_processed: true) : invalid_names_posts_path %>
  
<div class="table-options swap-modes">
  <%= link_to invalid_names_posts_path_link, class: "waves-effect waves-light btn-small indigo darken-4 table-option" do %>
    <i class="material-icons left">chevron_left</i>
    View Mismatched Facebook Names
  <% end %>
</div>
<div class="table-options">
  <%= link_to view_posts_path_link, class: "waves-effect waves-light btn-small orange lighten-2 table-option" do %>
    <i class="material-icons left"><%= @show_processed ? "remove" : "add" %></i>
    <%= @show_processed ? "Hide Processed Data" : "Show Processed Data" %>
  <% end %>
  <%= link_to refresh_posts_path, class: "waves-effect waves-light btn-small orange darken-2 table-option" do %>
    <i class="material-icons left">sync</i>
    Update Site Data
  <% end %>
</div>

<% if @posts.length == 0 %>
  <div class="collection empty_collection">
    No posts right now! Click the "Update Site Data" button to import posts!
  </div>
<% end %>