config/routes.rb
Rails.application.routes.draw do

  # Dashboard routes
  resource :posts, only: [] do
    get  :view
    get  :invalid_names
    get  :refresh
    post :edit
  end
  root to: "posts#view"

  # Session routes
  resources :sessions , only: [:create, :destroy, :login]
  get 'auth/:provider/callback',       to: 'sessions#create'
  get 'auth/failure',                  to: redirect('/')
  get 'signout',                       to: 'sessions#destroy', as: 'signout'
  get 'signin',                        to: 'sessions#login',   as: 'signin'
end

app/views/layouts/_nav.html.erb
<nav class="blue darken-4">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo noselect">a2f Summer Challenge</a>
    <div class="nav_item nav_logout">
      <%= link_to signout_path, class: "waves-effect waves-light btn-small logout red lighten-2" do %>
        <i class="material-icons left">exit_to_app</i>
        Sign out
      <% end %>
    </div>
    <div class="nav_item">
      <span class="nav_userIcon">
        <% if current_user.profile_img == nil %>
          <i class="material-icons">account_circle</i>
        <% else %>
          <img src="<%= current_user.profile_img %>" class="profile" />
        <% end %>
      </span>
    </div>
    <div class="nav_item noselect">
      <%= current_user.name %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>a2f Summer Challenge Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notice animated fadeIn green lighten-2 <%= current_user == nil ? "wide-notice" : "" %>">
        <i class="material-icons">check_circle</i>
        <span class="notice-text">
          <%= raw(flash[:notice]) %>
        </span>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="notice animated fadeIn red lighten-3 <%= current_user == nil ? "wide-notice" : "" %>">
        <i class="material-icons">check_circle</i>
        <span class="notice-text">
          <%= raw(flash[:error]) %>
        </span>
      </div>
    <% end %>

    <% if current_user %>
      <div class="content">
        <% cache([current_user, "web_view"]) do %>
          <%= render "layouts/nav" %>
        <% end %>

        <div class="container">
          <%= content_for?(:admins) ? yield(:admins) : yield %>
          <%= render "posts/data_table" %>
        </div>
      </div>

    <% else %>
      <div class="content signIn">
        <div class="signIn-container">
          <%= yield %>
        </div>
      </div>
    <% end %>


  </body>
</html>